/**
 * generated by Xtext
 */
package org.xtext.validation;

import org.xtext.validation.AbstractScenarioValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ScenarioValidator extends AbstractScenarioValidator {
}
