/**
 * generated by Xtext
 */
package org.xtext.serializer;

import org.xtext.serializer.AbstractScenarioSyntacticSequencer;

@SuppressWarnings("all")
public class ScenarioSyntacticSequencer extends AbstractScenarioSyntacticSequencer {
}
