/**
 * generated by Xtext
 */
package org.xtext.serializer;

import org.xtext.serializer.AbstractScenarioSemanticSequencer;

@SuppressWarnings("all")
public class ScenarioSemanticSequencer extends AbstractScenarioSemanticSequencer {
}
