/*
 * generated by Xtext
 */
package org.xtext.ui.contentassist

import org.xtext.ui.contentassist.AbstractScenarioProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class ScenarioProposalProvider extends AbstractScenarioProposalProvider {
}
