/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScenarioUiModule extends org.xtext.ui.AbstractScenarioUiModule {
	public ScenarioUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
