/*
* generated by Xtext
*/
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.ScenarioGrammarAccess;

public class ScenarioParser extends AbstractContentAssistParser {
	
	@Inject
	private ScenarioGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalScenarioParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalScenarioParser result = new org.xtext.ui.contentassist.antlr.internal.InternalScenarioParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getOurObjectAccess().getAlternatives(), "rule__OurObject__Alternatives");
					put(grammarAccess.getCapabilityAccess().getAlternatives(), "rule__Capability__Alternatives");
					put(grammarAccess.getComponentUAccess().getAlternatives(), "rule__ComponentU__Alternatives");
					put(grammarAccess.getConstraintAccess().getAlternatives(), "rule__Constraint__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanObjectAccess().getAlternatives(), "rule__EBooleanObject__Alternatives");
					put(grammarAccess.getEFloatOurObjectAccess().getAlternatives_4_0(), "rule__EFloatOurObject__Alternatives_4_0");
					put(grammarAccess.getEDoubleObjectAccess().getAlternatives_4_0(), "rule__EDoubleObject__Alternatives_4_0");
					put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
					put(grammarAccess.getScenarioAccess().getGroup_1(), "rule__Scenario__Group_1__0");
					put(grammarAccess.getOurObject_ImplAccess().getGroup(), "rule__OurObject_Impl__Group__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup(), "rule__Capability_Impl__Group__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_7(), "rule__Capability_Impl__Group_7__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_8(), "rule__Capability_Impl__Group_8__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_9(), "rule__Capability_Impl__Group_9__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_10(), "rule__Capability_Impl__Group_10__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_11(), "rule__Capability_Impl__Group_11__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_12(), "rule__Capability_Impl__Group_12__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_12_3(), "rule__Capability_Impl__Group_12_3__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_13(), "rule__Capability_Impl__Group_13__0");
					put(grammarAccess.getCapability_ImplAccess().getGroup_13_3(), "rule__Capability_Impl__Group_13_3__0");
					put(grammarAccess.getCapabilityProvisionAccess().getGroup(), "rule__CapabilityProvision__Group__0");
					put(grammarAccess.getCapabilityProvisionAccess().getGroup_5(), "rule__CapabilityProvision__Group_5__0");
					put(grammarAccess.getCapabilityProvisionAccess().getGroup_6(), "rule__CapabilityProvision__Group_6__0");
					put(grammarAccess.getCapabilityProvisionAccess().getGroup_7(), "rule__CapabilityProvision__Group_7__0");
					put(grammarAccess.getCapabilityProvisionAccess().getGroup_8(), "rule__CapabilityProvision__Group_8__0");
					put(grammarAccess.getQualitativeValueDictionaryAccess().getGroup(), "rule__QualitativeValueDictionary__Group__0");
					put(grammarAccess.getQualitativeValueDictionaryAccess().getGroup_2(), "rule__QualitativeValueDictionary__Group_2__0");
					put(grammarAccess.getQualitativeValueDictionaryAccess().getGroup_3(), "rule__QualitativeValueDictionary__Group_3__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_4(), "rule__Component__Group_4__0");
					put(grammarAccess.getComponentAccess().getGroup_5(), "rule__Component__Group_5__0");
					put(grammarAccess.getComponentAccess().getGroup_6(), "rule__Component__Group_6__0");
					put(grammarAccess.getComponentAccess().getGroup_7(), "rule__Component__Group_7__0");
					put(grammarAccess.getRunConfiguration_ImplAccess().getGroup(), "rule__RunConfiguration_Impl__Group__0");
					put(grammarAccess.getRunConfiguration_ImplAccess().getGroup_4(), "rule__RunConfiguration_Impl__Group_4__0");
					put(grammarAccess.getRunConfiguration_ImplAccess().getGroup_5(), "rule__RunConfiguration_Impl__Group_5__0");
					put(grammarAccess.getFindTradeOffsAccess().getGroup(), "rule__FindTradeOffs__Group__0");
					put(grammarAccess.getFindTradeOffsAccess().getGroup_4(), "rule__FindTradeOffs__Group_4__0");
					put(grammarAccess.getFindTradeOffsAccess().getGroup_5(), "rule__FindTradeOffs__Group_5__0");
					put(grammarAccess.getFindTradeOffsAccess().getGroup_6(), "rule__FindTradeOffs__Group_6__0");
					put(grammarAccess.getFindTradeOffsAccess().getGroup_7(), "rule__FindTradeOffs__Group_7__0");
					put(grammarAccess.getThroughLifePlanningAccess().getGroup(), "rule__ThroughLifePlanning__Group__0");
					put(grammarAccess.getThroughLifePlanningAccess().getGroup_4(), "rule__ThroughLifePlanning__Group_4__0");
					put(grammarAccess.getThroughLifePlanningAccess().getGroup_5(), "rule__ThroughLifePlanning__Group_5__0");
					put(grammarAccess.getThroughLifePlanningAccess().getGroup_6(), "rule__ThroughLifePlanning__Group_6__0");
					put(grammarAccess.getThroughLifePlanningAccess().getGroup_7(), "rule__ThroughLifePlanning__Group_7__0");
					put(grammarAccess.getThroughLifePlanningAccess().getGroup_8(), "rule__ThroughLifePlanning__Group_8__0");
					put(grammarAccess.getThroughLifePlanningAccess().getGroup_9(), "rule__ThroughLifePlanning__Group_9__0");
					put(grammarAccess.getEIntegerObjectAccess().getGroup(), "rule__EIntegerObject__Group__0");
					put(grammarAccess.getMeasurementAccess().getGroup(), "rule__Measurement__Group__0");
					put(grammarAccess.getMeasurementAccess().getGroup_4(), "rule__Measurement__Group_4__0");
					put(grammarAccess.getMeasurementAccess().getGroup_5(), "rule__Measurement__Group_5__0");
					put(grammarAccess.getMeasurementAccess().getGroup_6(), "rule__Measurement__Group_6__0");
					put(grammarAccess.getMeasurementAccess().getGroup_7(), "rule__Measurement__Group_7__0");
					put(grammarAccess.getMeasurementAccess().getGroup_7_3(), "rule__Measurement__Group_7_3__0");
					put(grammarAccess.getMeasurementAccess().getGroup_8(), "rule__Measurement__Group_8__0");
					put(grammarAccess.getMeasurementAccess().getGroup_8_3(), "rule__Measurement__Group_8_3__0");
					put(grammarAccess.getMeasurementAccess().getGroup_9(), "rule__Measurement__Group_9__0");
					put(grammarAccess.getMeasurementAccess().getGroup_9_3(), "rule__Measurement__Group_9_3__0");
					put(grammarAccess.getMeasurementAccess().getGroup_10(), "rule__Measurement__Group_10__0");
					put(grammarAccess.getEFloatOurObjectAccess().getGroup(), "rule__EFloatOurObject__Group__0");
					put(grammarAccess.getEFloatOurObjectAccess().getGroup_4(), "rule__EFloatOurObject__Group_4__0");
					put(grammarAccess.getQualitativeValueAccess().getGroup(), "rule__QualitativeValue__Group__0");
					put(grammarAccess.getCapabilityUpgradeAccess().getGroup(), "rule__CapabilityUpgrade__Group__0");
					put(grammarAccess.getCapabilityUpgradeAccess().getGroup_4(), "rule__CapabilityUpgrade__Group_4__0");
					put(grammarAccess.getCapabilityUpgradeAccess().getGroup_5(), "rule__CapabilityUpgrade__Group_5__0");
					put(grammarAccess.getCapabilityUpgradeAccess().getGroup_6(), "rule__CapabilityUpgrade__Group_6__0");
					put(grammarAccess.getCost_ImplAccess().getGroup(), "rule__Cost_Impl__Group__0");
					put(grammarAccess.getCost_ImplAccess().getGroup_4(), "rule__Cost_Impl__Group_4__0");
					put(grammarAccess.getCost_ImplAccess().getGroup_4_1(), "rule__Cost_Impl__Group_4_1__0");
					put(grammarAccess.getCost_ImplAccess().getGroup_4_2(), "rule__Cost_Impl__Group_4_2__0");
					put(grammarAccess.getCost_ImplAccess().getGroup_4_3(), "rule__Cost_Impl__Group_4_3__0");
					put(grammarAccess.getCapabilityChangeAccess().getGroup(), "rule__CapabilityChange__Group__0");
					put(grammarAccess.getCapabilityChangeAccess().getGroup_4(), "rule__CapabilityChange__Group_4__0");
					put(grammarAccess.getComponentU_ImplAccess().getGroup(), "rule__ComponentU_Impl__Group__0");
					put(grammarAccess.getExistingComponentAccess().getGroup(), "rule__ExistingComponent__Group__0");
					put(grammarAccess.getExistingComponentAccess().getGroup_4(), "rule__ExistingComponent__Group_4__0");
					put(grammarAccess.getExistingComponentAccess().getGroup_5(), "rule__ExistingComponent__Group_5__0");
					put(grammarAccess.getAcquirableComponentAccess().getGroup(), "rule__AcquirableComponent__Group__0");
					put(grammarAccess.getAcquirableComponentAccess().getGroup_4(), "rule__AcquirableComponent__Group_4__0");
					put(grammarAccess.getAcquirableComponentAccess().getGroup_5(), "rule__AcquirableComponent__Group_5__0");
					put(grammarAccess.getConstraint_ImplAccess().getGroup(), "rule__Constraint_Impl__Group__0");
					put(grammarAccess.getDesireHighAccess().getGroup(), "rule__DesireHigh__Group__0");
					put(grammarAccess.getDesireLowAccess().getGroup(), "rule__DesireLow__Group__0");
					put(grammarAccess.getBudgetAccess().getGroup(), "rule__Budget__Group__0");
					put(grammarAccess.getBudgetAccess().getGroup_4(), "rule__Budget__Group_4__0");
					put(grammarAccess.getBudgetAccess().getGroup_5(), "rule__Budget__Group_5__0");
					put(grammarAccess.getBudgetAccess().getGroup_6(), "rule__Budget__Group_6__0");
					put(grammarAccess.getBudgetAccess().getGroup_7(), "rule__Budget__Group_7__0");
					put(grammarAccess.getEDoubleObjectAccess().getGroup(), "rule__EDoubleObject__Group__0");
					put(grammarAccess.getEDoubleObjectAccess().getGroup_4(), "rule__EDoubleObject__Group_4__0");
					put(grammarAccess.getScenarioAccess().getOurObjectsAssignment_1_0(), "rule__Scenario__OurObjectsAssignment_1_0");
					put(grammarAccess.getScenarioAccess().getOurObjectsAssignment_1_1(), "rule__Scenario__OurObjectsAssignment_1_1");
					put(grammarAccess.getCapability_ImplAccess().getStandAloneAssignment_1(), "rule__Capability_Impl__StandAloneAssignment_1");
					put(grammarAccess.getCapability_ImplAccess().getSearchObjectiveAssignment_2(), "rule__Capability_Impl__SearchObjectiveAssignment_2");
					put(grammarAccess.getCapability_ImplAccess().getSequentialSchedulingAssignment_3(), "rule__Capability_Impl__SequentialSchedulingAssignment_3");
					put(grammarAccess.getCapability_ImplAccess().getNameAssignment_5(), "rule__Capability_Impl__NameAssignment_5");
					put(grammarAccess.getCapability_ImplAccess().getReuseAssignment_7_1(), "rule__Capability_Impl__ReuseAssignment_7_1");
					put(grammarAccess.getCapability_ImplAccess().getAccumulationAssignment_8_1(), "rule__Capability_Impl__AccumulationAssignment_8_1");
					put(grammarAccess.getCapability_ImplAccess().getStartDateAssignment_9_1(), "rule__Capability_Impl__StartDateAssignment_9_1");
					put(grammarAccess.getCapability_ImplAccess().getEndDateAssignment_10_1(), "rule__Capability_Impl__EndDateAssignment_10_1");
					put(grammarAccess.getCapability_ImplAccess().getMeasurementsAssignment_11_0(), "rule__Capability_Impl__MeasurementsAssignment_11_0");
					put(grammarAccess.getCapability_ImplAccess().getMeasurementsAssignment_11_1(), "rule__Capability_Impl__MeasurementsAssignment_11_1");
					put(grammarAccess.getCapability_ImplAccess().getDecomposesAssignment_12_2(), "rule__Capability_Impl__DecomposesAssignment_12_2");
					put(grammarAccess.getCapability_ImplAccess().getDecomposesAssignment_12_3_1(), "rule__Capability_Impl__DecomposesAssignment_12_3_1");
					put(grammarAccess.getCapability_ImplAccess().getSatisfiedByAssignment_13_2(), "rule__Capability_Impl__SatisfiedByAssignment_13_2");
					put(grammarAccess.getCapability_ImplAccess().getSatisfiedByAssignment_13_3_1(), "rule__Capability_Impl__SatisfiedByAssignment_13_3_1");
					put(grammarAccess.getCapabilityProvisionAccess().getSearchObjectiveAssignment_1(), "rule__CapabilityProvision__SearchObjectiveAssignment_1");
					put(grammarAccess.getCapabilityProvisionAccess().getNameAssignment_3(), "rule__CapabilityProvision__NameAssignment_3");
					put(grammarAccess.getCapabilityProvisionAccess().getReuseAssignment_5_1(), "rule__CapabilityProvision__ReuseAssignment_5_1");
					put(grammarAccess.getCapabilityProvisionAccess().getStartDateAssignment_6_1(), "rule__CapabilityProvision__StartDateAssignment_6_1");
					put(grammarAccess.getCapabilityProvisionAccess().getEndDateAssignment_7_1(), "rule__CapabilityProvision__EndDateAssignment_7_1");
					put(grammarAccess.getCapabilityProvisionAccess().getMeasurementsAssignment_8_0(), "rule__CapabilityProvision__MeasurementsAssignment_8_0");
					put(grammarAccess.getCapabilityProvisionAccess().getMeasurementsAssignment_8_1(), "rule__CapabilityProvision__MeasurementsAssignment_8_1");
					put(grammarAccess.getQualitativeValueDictionaryAccess().getNameAssignment_1(), "rule__QualitativeValueDictionary__NameAssignment_1");
					put(grammarAccess.getQualitativeValueDictionaryAccess().getLessThanAssignment_2_1(), "rule__QualitativeValueDictionary__LessThanAssignment_2_1");
					put(grammarAccess.getQualitativeValueDictionaryAccess().getGreaterThanAssignment_3_1(), "rule__QualitativeValueDictionary__GreaterThanAssignment_3_1");
					put(grammarAccess.getComponentAccess().getNameAssignment_2(), "rule__Component__NameAssignment_2");
					put(grammarAccess.getComponentAccess().getProvidesAssignment_4_0(), "rule__Component__ProvidesAssignment_4_0");
					put(grammarAccess.getComponentAccess().getProvidesAssignment_4_1(), "rule__Component__ProvidesAssignment_4_1");
					put(grammarAccess.getComponentAccess().getUpgradesAssignment_5_0(), "rule__Component__UpgradesAssignment_5_0");
					put(grammarAccess.getComponentAccess().getUpgradesAssignment_5_1(), "rule__Component__UpgradesAssignment_5_1");
					put(grammarAccess.getComponentAccess().getRequiresAssignment_6_0(), "rule__Component__RequiresAssignment_6_0");
					put(grammarAccess.getComponentAccess().getRequiresAssignment_6_1(), "rule__Component__RequiresAssignment_6_1");
					put(grammarAccess.getComponentAccess().getCostsAssignment_7_0(), "rule__Component__CostsAssignment_7_0");
					put(grammarAccess.getComponentAccess().getCostsAssignment_7_1(), "rule__Component__CostsAssignment_7_1");
					put(grammarAccess.getRunConfiguration_ImplAccess().getNameAssignment_2(), "rule__RunConfiguration_Impl__NameAssignment_2");
					put(grammarAccess.getRunConfiguration_ImplAccess().getPopSizeAssignment_4_1(), "rule__RunConfiguration_Impl__PopSizeAssignment_4_1");
					put(grammarAccess.getRunConfiguration_ImplAccess().getGenCountAssignment_5_1(), "rule__RunConfiguration_Impl__GenCountAssignment_5_1");
					put(grammarAccess.getFindTradeOffsAccess().getNameAssignment_2(), "rule__FindTradeOffs__NameAssignment_2");
					put(grammarAccess.getFindTradeOffsAccess().getPopSizeAssignment_4_1(), "rule__FindTradeOffs__PopSizeAssignment_4_1");
					put(grammarAccess.getFindTradeOffsAccess().getGenCountAssignment_5_1(), "rule__FindTradeOffs__GenCountAssignment_5_1");
					put(grammarAccess.getFindTradeOffsAccess().getComponentsAssignment_6_0(), "rule__FindTradeOffs__ComponentsAssignment_6_0");
					put(grammarAccess.getFindTradeOffsAccess().getComponentsAssignment_6_1(), "rule__FindTradeOffs__ComponentsAssignment_6_1");
					put(grammarAccess.getFindTradeOffsAccess().getConstraintsAssignment_7_0(), "rule__FindTradeOffs__ConstraintsAssignment_7_0");
					put(grammarAccess.getFindTradeOffsAccess().getConstraintsAssignment_7_1(), "rule__FindTradeOffs__ConstraintsAssignment_7_1");
					put(grammarAccess.getThroughLifePlanningAccess().getNameAssignment_2(), "rule__ThroughLifePlanning__NameAssignment_2");
					put(grammarAccess.getThroughLifePlanningAccess().getPopSizeAssignment_4_1(), "rule__ThroughLifePlanning__PopSizeAssignment_4_1");
					put(grammarAccess.getThroughLifePlanningAccess().getGenCountAssignment_5_1(), "rule__ThroughLifePlanning__GenCountAssignment_5_1");
					put(grammarAccess.getThroughLifePlanningAccess().getStartDateAssignment_6_1(), "rule__ThroughLifePlanning__StartDateAssignment_6_1");
					put(grammarAccess.getThroughLifePlanningAccess().getEndDateAssignment_7_1(), "rule__ThroughLifePlanning__EndDateAssignment_7_1");
					put(grammarAccess.getThroughLifePlanningAccess().getComponentsAssignment_8_0(), "rule__ThroughLifePlanning__ComponentsAssignment_8_0");
					put(grammarAccess.getThroughLifePlanningAccess().getComponentsAssignment_8_1(), "rule__ThroughLifePlanning__ComponentsAssignment_8_1");
					put(grammarAccess.getThroughLifePlanningAccess().getConstraintsAssignment_9_0(), "rule__ThroughLifePlanning__ConstraintsAssignment_9_0");
					put(grammarAccess.getThroughLifePlanningAccess().getConstraintsAssignment_9_1(), "rule__ThroughLifePlanning__ConstraintsAssignment_9_1");
					put(grammarAccess.getMeasurementAccess().getNameAssignment_2(), "rule__Measurement__NameAssignment_2");
					put(grammarAccess.getMeasurementAccess().getCriticalValueAssignment_4_1(), "rule__Measurement__CriticalValueAssignment_4_1");
					put(grammarAccess.getMeasurementAccess().getBenchmarkValueAssignment_5_1(), "rule__Measurement__BenchmarkValueAssignment_5_1");
					put(grammarAccess.getMeasurementAccess().getProvidedValueAssignment_6_1(), "rule__Measurement__ProvidedValueAssignment_6_1");
					put(grammarAccess.getMeasurementAccess().getCriticalValuesAssignment_7_2(), "rule__Measurement__CriticalValuesAssignment_7_2");
					put(grammarAccess.getMeasurementAccess().getCriticalValuesAssignment_7_3_1(), "rule__Measurement__CriticalValuesAssignment_7_3_1");
					put(grammarAccess.getMeasurementAccess().getBenchmarkValuesAssignment_8_2(), "rule__Measurement__BenchmarkValuesAssignment_8_2");
					put(grammarAccess.getMeasurementAccess().getBenchmarkValuesAssignment_8_3_1(), "rule__Measurement__BenchmarkValuesAssignment_8_3_1");
					put(grammarAccess.getMeasurementAccess().getProvidedValuesAssignment_9_2(), "rule__Measurement__ProvidedValuesAssignment_9_2");
					put(grammarAccess.getMeasurementAccess().getProvidedValuesAssignment_9_3_1(), "rule__Measurement__ProvidedValuesAssignment_9_3_1");
					put(grammarAccess.getMeasurementAccess().getScriptAssignment_10_1(), "rule__Measurement__ScriptAssignment_10_1");
					put(grammarAccess.getQualitativeValueAccess().getNameAssignment_1(), "rule__QualitativeValue__NameAssignment_1");
					put(grammarAccess.getCapabilityUpgradeAccess().getNameAssignment_2(), "rule__CapabilityUpgrade__NameAssignment_2");
					put(grammarAccess.getCapabilityUpgradeAccess().getTargetComponentAssignment_4_1(), "rule__CapabilityUpgrade__TargetComponentAssignment_4_1");
					put(grammarAccess.getCapabilityUpgradeAccess().getUpgradingAssignment_5_1(), "rule__CapabilityUpgrade__UpgradingAssignment_5_1");
					put(grammarAccess.getCapabilityUpgradeAccess().getCapabilityChangesAssignment_6_0(), "rule__CapabilityUpgrade__CapabilityChangesAssignment_6_0");
					put(grammarAccess.getCapabilityUpgradeAccess().getCapabilityChangesAssignment_6_1(), "rule__CapabilityUpgrade__CapabilityChangesAssignment_6_1");
					put(grammarAccess.getCost_ImplAccess().getNameAssignment_2(), "rule__Cost_Impl__NameAssignment_2");
					put(grammarAccess.getCost_ImplAccess().getAmountAssignment_3(), "rule__Cost_Impl__AmountAssignment_3");
					put(grammarAccess.getCost_ImplAccess().getStartAfterAssignment_4_1_1(), "rule__Cost_Impl__StartAfterAssignment_4_1_1");
					put(grammarAccess.getCost_ImplAccess().getRepeatDurationAssignment_4_2_1(), "rule__Cost_Impl__RepeatDurationAssignment_4_2_1");
					put(grammarAccess.getCost_ImplAccess().getStopAfterAssignment_4_3_1(), "rule__Cost_Impl__StopAfterAssignment_4_3_1");
					put(grammarAccess.getCapabilityChangeAccess().getNameAssignment_2(), "rule__CapabilityChange__NameAssignment_2");
					put(grammarAccess.getCapabilityChangeAccess().getCapabilitiesAssignment_4_0(), "rule__CapabilityChange__CapabilitiesAssignment_4_0");
					put(grammarAccess.getCapabilityChangeAccess().getCapabilitiesAssignment_4_1(), "rule__CapabilityChange__CapabilitiesAssignment_4_1");
					put(grammarAccess.getComponentU_ImplAccess().getNameAssignment_2(), "rule__ComponentU_Impl__NameAssignment_2");
					put(grammarAccess.getComponentU_ImplAccess().getQuantityAssignment_3(), "rule__ComponentU_Impl__QuantityAssignment_3");
					put(grammarAccess.getExistingComponentAccess().getNameAssignment_2(), "rule__ExistingComponent__NameAssignment_2");
					put(grammarAccess.getExistingComponentAccess().getQuantityAssignment_3(), "rule__ExistingComponent__QuantityAssignment_3");
					put(grammarAccess.getExistingComponentAccess().getStartDateAssignment_4_1(), "rule__ExistingComponent__StartDateAssignment_4_1");
					put(grammarAccess.getExistingComponentAccess().getEndDateAssignment_5_1(), "rule__ExistingComponent__EndDateAssignment_5_1");
					put(grammarAccess.getAcquirableComponentAccess().getNameAssignment_2(), "rule__AcquirableComponent__NameAssignment_2");
					put(grammarAccess.getAcquirableComponentAccess().getQuantityAssignment_3(), "rule__AcquirableComponent__QuantityAssignment_3");
					put(grammarAccess.getAcquirableComponentAccess().getAcquisitionTimeAssignment_4_1(), "rule__AcquirableComponent__AcquisitionTimeAssignment_4_1");
					put(grammarAccess.getAcquirableComponentAccess().getLifeSpanAssignment_5_1(), "rule__AcquirableComponent__LifeSpanAssignment_5_1");
					put(grammarAccess.getDesireHighAccess().getNameAssignment_2(), "rule__DesireHigh__NameAssignment_2");
					put(grammarAccess.getDesireLowAccess().getNameAssignment_2(), "rule__DesireLow__NameAssignment_2");
					put(grammarAccess.getBudgetAccess().getNameAssignment_2(), "rule__Budget__NameAssignment_2");
					put(grammarAccess.getBudgetAccess().getAmountAssignment_4_1(), "rule__Budget__AmountAssignment_4_1");
					put(grammarAccess.getBudgetAccess().getStartDateAssignment_5_1(), "rule__Budget__StartDateAssignment_5_1");
					put(grammarAccess.getBudgetAccess().getRepeatDurationAssignment_6_1(), "rule__Budget__RepeatDurationAssignment_6_1");
					put(grammarAccess.getBudgetAccess().getEndDateAssignment_7_1(), "rule__Budget__EndDateAssignment_7_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalScenarioParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalScenarioParser) parser;
			typedParser.entryRuleScenario();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ScenarioGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScenarioGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
